version: 0.2
phases:
  pre_build:
    commands:
      - echo "=== Logging in to Amazon ECR ==="
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - |
        # Read VERSION file
        echo "=== Reading VERSION file for image tag ==="
        VERSION_TAG=$(cat VERSION | tr -d '\n\r ')
        echo "Using image tag: $VERSION_TAG"
        
        # Check if image tag already exists in ECR
        echo "=== Checking if image tag already exists in ECR ==="
        EXISTING_TAGS=$(aws ecr describe-images --repository-name $ECR_REPOSITORY_NAME --region $AWS_REGION --query 'imageDetails[*].imageTags[]' --output text 2>/dev/null || echo "")
        
        if echo "$EXISTING_TAGS" | grep -qw "$VERSION_TAG"; then
          echo "Image tag $VERSION_TAG already exists in ECR. Skipping build and push."
          SKIP_BUILD="true"
        else
          echo "Image tag $VERSION_TAG not found in ECR. Proceeding with build."
          SKIP_BUILD="false"
          echo "=== Build started on $(date) ==="
          echo "Building the Docker image..."
          docker build -t $ECR_REPOSITORY_URI:$VERSION_TAG .
          docker tag $ECR_REPOSITORY_URI:$VERSION_TAG $ECR_REPOSITORY_URI:latest
        fi
        
        # Post build actions
        echo "=== Post build phase on $(date) ==="
        if [ "$SKIP_BUILD" = "false" ]; then
          docker images
          echo "Pushing the Docker images..."
          docker push $ECR_REPOSITORY_URI:$VERSION_TAG
          docker push $ECR_REPOSITORY_URI:latest
        else
          echo "Build was skipped, no images to push."
        fi
        
        # Write image definitions file
        echo "Writing image definitions file..."
        printf '[{"name":"wordpress","imageUri":"%s"}]' $ECR_REPOSITORY_URI:$VERSION_TAG > imagedefinitions.json
        
        # Save VERSION_TAG for next stage
        echo "$VERSION_TAG" > version_tag.txt
        echo "Build stage completed successfully"
artifacts:
  files:
    - imagedefinitions.json
    - version_tag.txt
