version: 0.2
phases:
  pre_build:
    commands:
      - echo "=== Checking VERSION file ==="
      - test -f VERSION || (echo "ERROR VERSION file not found!" && exit 1)
      - echo "VERSION file exists"
      - export VERSION_TAG=$(cat VERSION | tr -d '\n\r ')
      - echo "Version tag from file $VERSION_TAG"
      - test -n "$VERSION_TAG" || (echo "ERROR VERSION file is empty!" && exit 1)
      - echo "=== Checking for duplicate tags in ECR ==="
      - export EXISTING_TAGS=$(aws ecr describe-images --repository-name $ECR_REPOSITORY_NAME --region $AWS_REGION --query 'imageDetails[*].imageTags[*]' --output text 2>/dev/null || echo "")
      - echo "Existing tags in ECR"
      - echo "$EXISTING_TAGS"
      - '! echo "$EXISTING_TAGS" | grep -qw "$VERSION_TAG" || (echo "ERROR Tag $VERSION_TAG already exists in ECR!" && echo "Please update the VERSION file with a unique tag." && exit 1)'
      - echo "SUCCESS Tag $VERSION_TAG is unique and can be used"
      - echo "Verification complete"
  build:
    commands:
      - echo "=== Determining Blue-Green Deployment Target ==="
      - BLUE_COUNT=$(aws ecs describe-services --cluster $ECS_CLUSTER_NAME --services $BLUE_SERVICE_NAME --region $AWS_REGION --query 'services[0].desiredCount' --output text 2>/dev/null || echo "0")
      - echo "Blue service desired count $BLUE_COUNT"
      - |
        if [ "$BLUE_COUNT" -gt 0 ]; then
          export DEPLOYMENT_TARGET="green"
          echo "Blue is active, deploying to GREEN environment"
        else
          export DEPLOYMENT_TARGET="blue"
          echo "Green is active, deploying to BLUE environment"
        fi
      - echo "Deployment target $DEPLOYMENT_TARGET"
